### ISSUE TITLE
Dev server needs cache control headers

### ISSUE THREAD

**Issue by camdendotlol** [cu-mkp/editioncrafter-cli#21]
While making frequent changes to the CLI app during development, I'm constantly being served old versions of the manifests after updating them. This is really getting in the way of development, because I have to fight with the server and with my browser to get the newly-updated files in the EditionCrafter frontend.

It appears that `http-server` needs to pass headers to tell browsers not to cache responses: https://stackoverflow.com/questions/38295463/node-http-server-not-serving-updated-html-files

Should be a simple fix, I'll do it in a separate branch when I'm finished with the annotation work.

**Comment by NickLaiacona** [comment]
I see that this caching directive is not part of the start script in package.json:

`"start": "node_modules/.bin/http-server -c-1 -p 8080 --cors"`

Can we mark this as resolved?

**Comment by camdendotlol** [comment]
Yes, I ended up just putting the change in my most recent PR.
